services:
  redis:
    image: redis
    container_name: redis-container
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    # Removed ports to keep internal

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Removed ports to keep internal

  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: backend-container
    environment:
      FLASK_SECRET_KEY: 25BC196631D5BABC8AFEFAAB8BEAD
      GOOGLE_CLIENT_ID: 915940246324-ngdnehtq3unlscmnog7uq0qua8g67bcd.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      DATABASE_URL: postgresql://postgres:postgres@postgres/db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_APP: app
    depends_on:
      - redis
      - postgres
    # Removed ports to keep internal

  frontend:
    build: ../tf_frontend
    container_name: frontend-container
    environment:
      NEXT_PUBLIC_API_URL: /api
      GOOGLE_CLIENT_ID: 915940246324-ngdnehtq3unlscmnog7uq0qua8g67bcd.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      FLASK_GOOGLE_URL: http://backend-container:5000
      NEXT_PUBLIC_BACK_END_URL: /api
      IMGUR_CLIENT_ID: de5cd6c5436730a
      IMGUR_CLIENT_SECRET: a8e22188bc5c878a046327aaeee79b8bf75dd119
      NEXT_PUBLIC_IMGUR_CLIENT_ID: de5cd6c5436730a
    depends_on:
      - backend
    # Removed ports to keep internal

  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  redis-data:
  postgres-data: